### PR TITLE
fix(#19): support HTML content

### PR DESCRIPTION
**Pull request by ramseyfeng**
Adding support for HTML content display.

### CODE REVIEW

**Review by ThomasLeconte — CHANGES_REQUESTED** [review]
Hi,
I think an `html` property in `notifyOptions` should be better. You keep the given text, and html could be displayed additionaly if `html` property is not null.

Something like this : 
```ts
export type CreateNotifyOptions = {
  text: string;
  html?: string;
  level?: Level;
  location?: VSnackbar['$props']['location'];
  notifyOptions?: VSnackbar['$props'];
};
```

Moreover, you need to add `html` property to `index.d.ts`, `types.ts` for allowing autocompletion in projects using this library.

**Comment by ramseyfeng** [comment]
@ThomasLeconte Updated MR according to your comments.

**Review by ThomasLeconte — CHANGES_REQUESTED** [review]
Hi @ramseyfeng, thanks for your work.
In my opinion, `notifyInfo`, `notifyWarning`, `notifyError` and `notifySuccess` are fast ways to make notifications. HTML support is not a common use for snackbars. You can keep `htmlContent` in `CreateNotifyOptions`, but it's not necessary in all shortcuts functions.

**Review by ramseyfeng — COMMENTED** [review]
@ThomasLeconte The PR has been updated again. :p

**Review by ThomasLeconte — APPROVED** [review]
Nice ! I will test it soon and I will prevent you when next release is available 😉 !

**Comment by ThomasLeconte** [comment]
Hi @ramseyfeng, `1.5.3` version is available 😉 !

**Comment by ramseyfeng** [comment]
@ThomasLeconte That's great!

**Pull request merged**
